# Generated by Django 3.0.6 on 2020-05-27 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveStockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataType', models.CharField(choices=[('CURRENT', 'CURRENT'), ('CONSTANT', 'CONSTANT')], max_length=10)),
                ('production_type', models.CharField(choices=[('PRODUCTION', 'PRODUCTION'), ('INCREMENTS', 'INCREMENTS')], max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveStockGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('livestockdata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livestock.LiveStockData')),
                ('production_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livestock.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('livestockdata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livestock.LiveStockData')),
                ('price_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livestock.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='LiveStockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, unique=True)),
                ('LiveStockGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livestock.LiveStockGroup')),
            ],
        ),
        migrations.AddField(
            model_name='livestockdata',
            name='LiveStockItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.LiveStockItem'),
        ),
        migrations.AddField(
            model_name='livestockdata',
            name='Year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.Year'),
        ),
        migrations.AddField(
            model_name='livestockdata',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='livestock.District'),
        ),
    ]
