# Generated by Django 3.0.6 on 2020-05-19 14:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='baseyear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^[20]{2}\\d{2}[-][0-9]{2}$', 'Year Pattern is like 2011-12')], verbose_name='Base Year')),
            ],
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='subsector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('P', 'PRIMARY'), ('S', 'SECONDARY'), ('T', 'TERTIARY')], max_length=1, verbose_name='Sector')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Sub-Sector')),
            ],
        ),
        migrations.CreateModel(
            name='year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^[20]{2}\\d{2}[-][0-9]{2}$', 'Year Pattern is like 2011-12')], verbose_name='Year')),
            ],
        ),
        migrations.CreateModel(
            name='ddp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('CON', 'CONSTANT'), ('CUR', 'CURRENT')], max_length=3, verbose_name='Price Type')),
                ('value_in_crore', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numeric data is allowed.')], verbose_name='Value (In Crore Rs.)')),
                ('baseyear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.baseyear', verbose_name='Base Year')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.district', verbose_name='District')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.state', verbose_name='State')),
                ('subsector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.subsector', verbose_name='Sub Sector')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.year', verbose_name='Year')),
            ],
        ),
    ]
